config/routes.rb
Qualityexpressdrycleaners::Application.routes.draw do

  root 'static_pages#index'

  get 'contact' => 'static_pages#contact'
  get 'services' => 'static_pages#services'
  get 'about-us' => 'static_pages#about_us', as: 'about_us'
  get 'advice' => 'static_pages#advice'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="clearfix"></div>

<footer class="content">
  <div class="cont-block">
    <h3 class="f-title"><span>Contact info</span></h3>
    <ul class="cont-list">
      <li><b>Address:</b> <p>12 Upper Tooting Road, London, SW17 7PG.</p></li>
      <li><b>Phone Number:</b> 020 8767 1337</li>
      <li><b>Website:</b> http://qualityexpressdrycleaners.co.uk/</li>
    </ul>
    <ul class="social">
      <li class="face">
        <a href="https://www.facebook.com/pages/Quality-Express-Dry-Cleaners/568205449909521" target="_blank">face</a>
        <i class="social-name">facebook</i>
      </li>
      <li class="google">
        <a href="https://plus.google.com/116066614319558590904?gl=uk&hl=en" target="_blank">google</a>
        <i class="social-name">google</i>
      </li>
    </ul>
  </div>

  <div class="twit-block">
    <h3 class="f-title"><span>Map</span></h3>
    <div class="contact-map">
      <div id="map_canvas2" style="width:100%; height:100%"></div>
    </div>
  </div><!--.twit-block-->

  <div class="clearfix"></div>
</footer>
</div><!--#wrapper-->

<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script>window.jQuery || document.write('<script src="js/vendors/jquery-1.9.1.js"><\/script>')</script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.min.js"></script>
<script src="js/vendors/bootstrap.js"></script>
<script src="js/vendors/instagram.js"></script>
<script src="js/vendors/superfish.js"></script>
<script src="js/vendors/jquery.colorbox.js"></script>
<script src="js/vendors/swipe.js"></script>
<script src="js/lazy-images.js"></script>
<script src="js/script.js"></script>
<script>
(function($) {
  var $body = $('body');
  $(window).on('resize.sliderReflow', function() {
    $('.slider-flip').height($('.slider-flip-front h3').height()+$('.slider-flip-front p').height()+67).css('bottom','-'+($('.slider-flip').height()/2+'px'));
    $('.home-prev, .home-next').css('top',$('.home-slide.swipe').height()/2+'px');

  }).trigger('resize.sliderReflow');
})(jQuery);
</script>
<script src="https://maps.google.com/maps/api/js?sensor=true"></script>
<script>
  (function initialize() {
    var latlng = new google.maps.LatLng(51.435415,-0.160503);
    var myOptions = {
      zoom: 15,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map_canvas2"),
        myOptions);
    var marker = new google.maps.Marker({
        position: latlng,
        map: map,
        title: 'Quality Express Dry Cleaners'
    });

  })();
</script>
<script>
$(function() {
  setTimeout(function(){ $('.active').mouseover(); }, 100);
});
</script>

app/views/layouts/_header.html.erb
<header>
  <div class="header" id="header">
    <h1 class="logo"><a href="<%= root_path %>">Quality Express</a><p><a href="<%= root_path %>">Dry Cleaners</a></p></h1>
    <ul class="head-menu">
      <li class="border-a"></li>
      <li class="<%= "active" if params[:action] == "index" %>">
        <a href="<%= root_path %>">Home</a>
      </li>
      <li class="<%= "active" if params[:action] == "services" %>">
        <a href="<%= services_path %>">Services</a>
      </li>
      <li class="<%= "active" if params[:action] == "advice" %>">
        <a href="<%= advice_path %>">Advice</a>
      </li>
      <li class="<%= "active" if params[:action] == "contact" %>">
        <a href="<%= contact_path %>">Contacts</a>
      </li>
    </ul><!--.head-menu-->
    <div class="search">
      <input type="search">
      <button>search</button>
    </div><!--.search-->
  </div><!--#header.header-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="keywords" content="Tooting Bec, Dry Cleaners, Quality Express">
  <meta name="description" content="Tooting Bec Dry Cleaners, Quality Express, Dry Cleaners">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
  <title>Quality Express Dry Cleaners</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700,700italic&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <link rel="stylesheet" href="css/bootstrap.css">
  <link rel="stylesheet" href="css/colorbox.css">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/slider-2.css">
  <!--[if IE 8]>
    <link rel="stylesheet" href="css/ie8.css" />
  <![endif]-->
  <!--[if lt IE 8]>
    <link rel="stylesheet" href="css/ie7.css" />
    <script type="text/javascript" src="js/ie.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/advice.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
  <link rel="stylesheet" href="css/bootstrap.css">
  <link rel="stylesheet" href="css/colorbox.css">
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div id="wrapper">
    <%= render 'layouts/header' %>
    <div class="title-p-bg">
      <div class="wrapper-content title-page">
        <div class="content">
          <h3>Advice</h3>
        </div>
      </div>
    </div><!--.title-p-bg-->

    <div class="clearfix"></div>

    <div class="content pt-61 page-content">

      <aside>
        <div class="block">
          <h3 class="aside-title">Garment Advice</h3>
          <ul class="blog-categories">
            <li><a href="#" onclick="toggle_visibility('stains');"><i></i>Stains</a></li>
            <li><a href="#" onclick="toggle_visibility('garment');"><i></i>Garment care</a></li>
            <li><a href="#" onclick="toggle_visibility('linen');"><i></i>Linen care</a></li>
          </ul>
        </div><!--.block-->
      </aside>

      <div class="blog">
        <div id="stains" class='hide' style='display: block;'>
          <h4>Stains</h4>
          <ul>
            <li>The nature and age of any stain combined with the colour and construction of the fabric very much dictates the end result.</li>
            <li>The dye in some fabrics is more soluble than the stain. Removing the stain will remove the dye.</li>
            <li>Developed Stains: Spillages of drinks not containing strong dyes, such as lemonade and champagne, can be blotted away from fabrics and appear to have disappeared. However the residual sugar content is at work in your garment. Left unattended for a period of time, a yellow or brown stain will appear, this is due to oxidation of the sugar, similar to a half eaten apple.</li>
            <li>Early on in its life a stain will develop with the help of any heat source, such as pressing. The resulting developed stain can be permanent.</li>
          </ul>
          <p>Stains are dealt with by hand prior to dry cleaning. Unless we have discussed with you the element of ‘Owners Risk’ we will operate within safety margins, limiting the end result in the removal of problematic stains.<br></p>
        </div>
        <div id="garment" class='hide'>
        <h4>Garment care</h4>
        <ul>
          <li>Hang clothes outside your wardrobe for at least two hours before putting away.</li>
          <li>Cover the shoulders of clothing; use a cut off dry cleaning cover, to prevent dust. Do not leave in the wardrobe completely covered as the air cannot circulate.</li>
          <li>Deal with stained clothes as soon as possible. Stains left unattended may develop and damage the fabric.</li>
          <li>Never rub stains, blot with a white absorbent paper towel – one piece in front and one behind.</li>
          <li>Rubbing at silk, wool or linen may result in permanent removal of the dye which becomes more apparent after dry cleaning.</li>
          <li>Rubbing wool may cause pile damage.</li>
          <li>Do not be tempted to apply white wine, soda water, salt etc. to stains it makes the stain more problematic to deal with.</li>
          <li>Dry cleaning relates best to oil based stains, never dab water on these as water sets the oils into the fabric.</li>
          <li>Water based stains are more difficult to deal with and can loosen the dye in fabrics. Application of water will exacerbate the problem.</li>
          <li>Always tell your dry cleaner what caused the stain and what you have done in the attempt to remove it.</li>
          <li>Dress for the occasion. If attending a ‘High Risk’ event where drink can spill over you (cocktail party), wear something washable.</li>
        </ul>
          We advise on all areas of fabric care. Information on your garments is essential to that advice, so please try and make time to discuss your needs when you visit us.<br>
        </div>
        <div id="linen" class='hide'>
        <h4>Linen care</h4>
        <ul>
          <li>Regular and careful laundering of linen is essential to preserve its colour.</li>
          <li>Never store used linen.
          Never store starched linen. The starch will discolour turning your linen yellow.</li>
          <li>Always keep linen in well ventilated cupboards first covering the shelves with acid free tissue paper. Our linen will always be returned in such paper which you can use for this purpose.</li>
          <li>Folded linen should always be kept away from direct sunlight. The latter will fade and discolour the fabrics along the fold lines.</li>
          <li>Try to avoid storing linen in draws as moths attack poorly ventilated darken areas. Wide slatted shelves allow the circulation of air.</li>
          <li>Ideally linen cupboards should be properly cleaned annually and your linen examined. Bed linen will show the first signs of wear in the middle, the fabric discolouring and becoming thin.</li>
        </ul>
        We have retained and encourage old-fashioned skills to ensure the highest standards of Quality Laundry.<br>
      </div><!--.blog-->

    </div><!--.content.pt-61-->

    <div class="clearfix"></div>

    <%= render 'layouts/footer' %>
  </div><!--#wrapper-->
  <script type="text/javascript">
    function toggle_visibility(id) {
       $('.hide').hide();
       var e = document.getElementById(id);

          e.style.display = 'block';
    }
  </script>
</body>
</html>

app/views/static_pages/contact.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
	<link rel="stylesheet" href="css/bootstrap.css">
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
	<div id="wrapper">
		<%= render 'layouts/header' %>
		<div class="title-p-bg">
			<div class="wrapper-content title-page">
				<div class="content">
					<h3>contacts</h3>
				</div>
			</div>
		</div><!--.title-p-bg-->

		<div class="clearfix"></div>

		<div class="content pt-61 page-content">

			<aside>
				<div class="block">
					<h3 class="aside-title">Get social</h3>
					<ul class="social">
						<li><a class="facebook" href="https://www.facebook.com/pages/Quality-Express-Dry-Cleaners/568205449909521" target="_blank"><i></i>Facebook</a></li>
						<li><a class="dribbble" href="https://plus.google.com/116066614319558590904?gl=uk&hl=en" target="_blank"><i></i>Google</a></li>
					</ul><!--.social-->
				</div><!--.block-->
				<div class="block pb-27">
					<h3 class="aside-title">Contact Info</h3>
					<ul class="contact-info">
						<li class="phone-ico"><strong>Phone:</strong> 020 87671337</li>
						<li class="fax-ico"><strong>Address:</strong> <p>12 Upper Tooting Road, London, SW17 7PG.</p></li>
					</ul><!--.contact-info-->
				</div><!--.block.pb-27-->
			</aside>

			<div class="contact-block">
				<h3 class="cont-title">Our location</h3>
				<p>We are located right next to Tooting Bec Underground Station on the nothern line, right next to the bus stop less than one minute walk from the station.</p>
				<h4>Tooting Bec, Tooting Bec Station (Stop C)</h4>
				<table class="table">
					<thead>
						<tr>
							<th>Bus #</th>
							<th>Location</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>155</td>
							<td>Newington</td>
						</tr>
						<tr>
							<td>219</td>
							<td>Clapham Junction</td>
						</tr>
						<tr>
							<td>355</td>
							<td>Brixton</td>
						</tr>
						<tr>
							<td>N155</td>
							<td>Soho</td>
						</tr>
					</tbody>
				</table>
				<h4>Map</h4>
				<div class="contact-map">
					<div id="map_canvas" style="width:100%; height:100%"></div>
				</div><!--.contact-map-->
				<form action="http://themes.myterranet.com/corporata/light-theme/contact.php" class="contact-us" id="contact-form" method="post" data-unknown-error-message="Unknown form error, please try again.">
					<fieldset>
						<h3>Send us your request</h3>
						<div class="control">
							<input name="name" type="text" placeholder="Name">
							<input name="email" type="text" placeholder="E-mail">
						</div>
						<div class="control">
							<textarea name="message" placeholder="Message" cols="30" rows="10"></textarea>
						</div>
						<div class="control mr-0">
							<button>SEND</button>
						</div>
					</fieldset>
				</form>
			</div><!--.contact-block-->

			<div class="clearfix"></div>

		</div><!--.content.pt-61-->

		<div class="clearfix"></div>
	</div><!--#wrapper-->

	<%= render 'layouts/footer' %>
	<script>
	  (function initialize() {
	    var latlng = new google.maps.LatLng(51.435415,-0.160503);
	    var myOptions = {
	      zoom: 15,
	      center: latlng,
	      mapTypeId: google.maps.MapTypeId.ROADMAP
	    };
	    var map = new google.maps.Map(document.getElementById("map_canvas"),
	        myOptions);
	    var marker = new google.maps.Marker({
	        position: latlng,
	        map: map,
	        title: 'Quality Express Dry Cleaners'
	    });
	  })();
	</script>

</body>
</html>

app/views/static_pages/index.html.erb
<div id="wrapper">
	<%= render 'layouts/header' %>
	<div class="wrapper-content">
		<div class="swipe home-slide video-swipe" data-swipe="mainFlip" data-auto="5000">
			<div class="swipe-wrap">
				<div data-title="" data-description="Quality Express has been established since 1970, offering professional dry cleaning and a personal laundry service to a high standard.
We are a family run business and are committed to providing the best possible service for our customers. We pride ourselves on providing a high quality service to all of our customers, as well as a a wide range of services that meets the cleaning needs of our customers.">
					<div class="img-block home">
						<%#= image_tag('banner.jpg') %>
					</div>
				</div>
			</div><!--.swipe-wrap-->
		</div><!--#mySwipe.swipe.home-slide-->
    <div class="content slider-flip">
      <div class="slider-flip-flipper">
        <div class="slider-flip-front"></div>
        <div class="slider-flip-back"></div>
      </div>
    </div>
	</div><!--.wrapper-content-->

	<div class="content">
		<div class="get-start">

		</div>

		<div class="clearfix"></div>

		<div class="row-fluid home-info">
			<div class="span4">
				<h3 class="item-1">Who we are?</h3>
				<p>We are a family run business that have been working hard for <%= Time.now.year - 1970 %> years and counting. We pride ourselves of the work we produce, for us it's about providing the customer the best possible service. We provide the same level of care and quality for each and every garment that comes to us.</p>
			</div>
			<div class="span4">
				<h3 class="item-2">Finest</h3>
				<p>The Dry Cleaning and Laundry Service offered by us combines the finest traditions of hand valeting with the most advanced, environmentally friendly techniques in fabric care.</p>
			</div>
			<div class="span4">
				<h3 class="item-3">Promise</h3>
				<p>Every garment that is brought to us goes through our unique seven stage process. Each item of clothing is carefully examined before any cleaning process is undertaken and hand finished before their return.</p>
			</div>
		</div><!--.row-fluid.home-info-->

		<div class="clearfix"></div>

		<div class="get-in">
			<a href="<%= contact_path %>">Get in touch</a>
			<span class="like-works">Like what you see?</span>
			<span class="sep"></span>
			<span class="can-do">Get in touch with us or drop us an email</span>
		</div><!--.get-in-->

	</div>

	<%= render 'layouts/footer' %>

app/views/static_pages/services.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
  <link rel="stylesheet" href="css/bootstrap.css">
  <link rel="stylesheet" href="css/colorbox.css">
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div id="wrapper">
    <%= render 'layouts/header' %>
    <div class="title-p-bg">
      <div class="wrapper-content title-page">
        <div class="content">
          <h3>Services</h3>
        </div>
      </div>
    </div><!--.title-p-bg-->

    <div class="clearfix"></div>

    <div class="content pt-61 page-content">

      <aside>
        <div class="block">
          <h3 class="aside-title">Services</h3>
          <ul class="blog-categories">
            <li><a href="#" onclick="toggle_visibility('dry_cleaning');"><i></i>Dry Cleaning</a></li>
            <li><a href="#" onclick="toggle_visibility('shirts');"><i></i>Shirts</a></li>
            <li><a href="#" onclick="toggle_visibility('laundering');"><i></i>Laundering</a></li>
            <li><a href="#" onclick="toggle_visibility('repairs');"><i></i>Repairs & Alterations</a></li>
            <li><a href="#" onclick="toggle_visibility('rugs');"><i></i>Rugs & Carpets</a></li>
            <li><a href="#" onclick="toggle_visibility('curtains');"><i></i>Curtains & Duvets</a></li>
            <li><a href="#" onclick="toggle_visibility('wedding');"><i></i>Wedding Dresses</a></li>
          </ul>
        </div><!--.block-->
      </aside>

      <div class="blog">
        <div id="dry_cleaning" class='hide' style='display: block;'><h4>Dry Cleaning</h4>We provide a combination of hand valeting with the most advanced and environmentally friendly techniques in fabric care.<br/><br/>
        Every piece, even everyday items, go through our seven stage cleaning process starting with an evaluation of the fabric and ending with a final hand inspection.</div>
        <div id="shirts" class='hide'><h4>Shirts</h4>Each shirt undergoes a pre-wash inspection, grading and treatment before being meticulously finished by hand.<br/><br/>
Shirts can be returned either folded or on a hanger, according to your preference.</div>
        <div id="laundering" class='hide'><h4>Laundering</h4>We pay particular attention to fine linen and cotton ware from table clothes to bathroom towels.<br/><br/>
This hand-finished service includes stain removal, cleaning, hand pressing, minor mending, inspection and packaging.</div>
        <div id="repairs" class='hide'><h4>Repairs & Alterations</h4>We bring expertise and dedication to repairs and alterations whether rejuvenating a garment or perfecting its fit. Special attention is always given to maintaining and, if necessary, expertly reproducing the finished detail of the garment. </div>
        <div id="rugs" class='hide'><h4>Rugs & Carpets</h4>The experts have mastered the techniques required to restore antique, silk and oriental rugs, tapestries, and household rugs. A damaged area, burns, splits and holes can be expertly mended, problem stains eliminated; colours rectified and faded areas restored.</div>
        <div id="curtains" class='hide'><h4>Curtains & Duvets</h4>We cleans and restores curtains so that textures are rejuvenated and colours given new vibrancy. We offer the finest cleaning of lined and interlined curtains with a ‘No Shrinkage Guarantee’.<br/><br/>
        Net curtains, tiebacks, Austrian, Festoon, Roman blinds and other forms of window dressing such as swags and tails can all be serviced. A take down and re-hang service is also available, by appointment.</div>
        <div id="wedding" class='hide'><h4>Wedding</h4>We offer Wedding dress cleaning and preservation. All dresses are carefully examined prior to being cleaned, fabrics are evaluated for serviceability and buttons or ornamental elements are protected or removed before the cleaning process.<br/><br/>
        For more information please contact our Couture Manager on 020 87671337 who will be happy to discuss your cleaning and preservation requirements.</div>
      </div><!--.blog-->

    </div><!--.content.pt-61-->

    <div class="clearfix"></div>

    <%= render 'layouts/footer' %>
  </div><!--#wrapper-->
  <script type="text/javascript">
    function toggle_visibility(id) {
       $('.hide').hide();
       var e = document.getElementById(id);

          e.style.display = 'block';
    }
  </script>
</body>
</html>